### ISSUE TITLE
Problems with react ^16.2.0

### ISSUE THREAD

**Issue by mam1konyan** [wiredmax/react-flags#10]
hey folks,

I'm using react v.16.2.0 in my project. After adding your component to my project I've faced issue:

TypeError: Cannot read property 'string' of undefined
(anonymous function)
node_modules/react-flags/lib/react-flags.js:97
    94 | 
    95 | propTypes: {
    96 |   // Alternative text of the flag <img> HTML tag.
>  97 |   alt: _react.PropTypes.string,
    98 | 
    99 |   // Base path to the content of /vendor
  100 |   basePath: _react.PropTypes.string,

Is it because of version that I'm using, or maybe there is a other reason of this error?)

**Comment by wiredmax** [comment]
@mam1konyan it's now fixed and a new version has been published on npm with support for React 16.

**Comment by michaelrodov** [comment]
Same error in 0.1.13 for react 15.6
This issue need to be reopened
