### ISSUE TITLE
Update react syntax

### ISSUE THREAD

**Issue by Koleok** [wiredmax/react-flags#7]
Per newer versions of react this needs to

- [x] Drop `createClass` syntax
- [x] use `prop-types` package instead of react built-in

**Comment by ryanashcraft** [comment]
@re7eal I discovered your fork and it has fixed this. Feel like making a PR? :)

https://github.com/re7eal/react-flags/commit/87c95ab207aeb5a13b77c9220359af1e74bf4b23

**Comment by re7eal** [comment]
@ryanashcraft There is a pull request which fixes this issue already but it doesn't get merged ([#9](https://github.com/wiredmax/react-flags/pull/9)).

**Comment by wiredmax** [comment]
@ryanashcraft @re7eal Sorry for the delay guys. I've merged #9 and published a new version on npm.

**Comment by Koleok** [comment]
@wiredmax thanks sir 👍
